#项目启动端口
server:
  port: 6029
  context-path: /

#spring 相关配置
spring:
  application:
    name: support-center-fund-job
  profiles:
    active: dev
  cloud:
    stream:
      instance-count: 2
      instance-index: 1
#spring cloud eureka
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 40
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.afsupportcenter.fundjob.entity
  plugins:
    - catMybatisInterceptor

  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
      cache-enabled: false


#xxl-job配置
logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: fund-job-executor
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: