export const PAYROLLTEMPLOYEE_SETLIST = "PAYROLLTEMPLOYEE_SETLIST"
export const PAYROLLTEMPLOYEE_GETLIST = "PAYROLLTEMPLOYEE_GETLIST"
export const PAYROLLTADDEMPLOYEE_SETLIST = "PAYROLLTADDEMPLOYEE_SETLIST"
export const PAYROLLTADDEMPLOYEE_GETLIST = "PAYROLLTADDEMPLOYEE_GETLIST"
