#mybatis:
#  mapperLocations: classpath*:mapper/**.xml
##  config-location: classpath:/mybatis-config.xml
#  configuration:
#    # map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.ciicsh.gto.salarymanagement.entity

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.afsupportcenter.credentialsqueryservice.entity.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true

server:
  port: 9111

app:
  id=10009999
endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false
  port: 9111
  context-path: /admin