spring:
  boot:
    admin:
      url: http://172.16.100.103:9625
      client:
        prefer-ip: true
  #spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.100.103:9602/eureka,http://172.16.100.104:9602/eureka"

druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_prd.properties