spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.9.15:3306/gtobusinessdb?useUnicode=true&useSSL=true&amp;characterEncoding=UTF-8
      username: root
      password: a111111
      max-active: 20
      min-idle: 8
      initial-size: 10
      validation-query: SELECT 'x'
      filter:
        stat:
          enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.9.11:9092
          zk-nodes: 172.16.9.11:2181
#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.21:9602/eureka/,http://172.16.9.20:9602/eureka/,http://172.16.9.19:9602/eureka/"  #开发注册中心eureka地址