spring:
  redis:
    database: 0
    host: 172.16.9.54
    port: 7001
    password: redis
    timeout: 1000
  boot:
    admin:
      url: http://172.16.9.56:9625
#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.56:9602/eureka"  #uat注册中心eureka地址

seaweed:
  masterHost: "172.16.9.58:9333"

druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_uat.properties
