info:
  app:
    name: AF支持中心
    version: 1.0.0
    description: 读接口
app:
  id: 10006010
  name: afsupportcenter-center-command-service
endpoints:
  shutdown:
    #启用shutdown
    enabled: true
    #禁用密码验证
    sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceurl}
logging:
  file: /tmp/logs/flexiblebenefitquery.log
management:
  context-path: /admin
  port: 6020
  #禁用安全验证
  security:
    enabled: false
server:
  port: 6019
  tomcat:
    background-processor-delay: 30
    basedir: /tmp
    max-threads: 0
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    uri-encoding: UTF-8
spring:
  application:
    name: afsupportcenter-center-command-service
  profiles:
    active: dev
  http:
    encoding:
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    converters:
      preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  datasource:
        url: jdbc:mysql://${database.host}:${database.port}/${database.databasename}?characterEncoding=utf8&useSSL=true
        username: ${database.username}
        password: ${database.password}
        driver-class-name: com.mysql.jdbc.Driver
  cloud:
      stream:
        kafka:
          binder:
            brokers: ${kafka.brokers}
            zk-nodes: ${kafka.zk-nodes}
        bindings:
          taskService-employeeEntry-useWorker-channel:
            destination: taskService-employeeEntry-useWorker # topic name
            group: ${spring.application.name}
            consumer:
              partitioned: true
          taskService-employeeEntry-socialSecurity-channel:
            destination: taskService-employeeEntry-socialSecurity # topic name
            group: ${spring.application.name}
            consumer:
              partitioned: true
          taskService-employeeEntry-contract-channel:
            destination: taskService-employeeEntry-contract # topic name
            group: ${spring.application.name}
            consumer:
              partitioned: true
mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #驼峰下划线转换
    db-column-underline: true
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  mapper-locations: mapper/*Mapper.xml
