spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.22.106:3306/gtobusinessdb?characterEncoding=utf8&useSSL=true
      username: root
      password: a111111
      max-active: 20
      min-idle: 8
      initial-size: 10
      validation-query: SELECT 'x'
      filter:
        stat:
          enabled: true
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: 172.16.9.55:9092
#          zk-nodes: 172.16.9.55:2181,172.16.9.56:2181,172.16.9.57:2181

#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.100.103:9602/eureka/,http://172.16.100.104:9602/eureka/"  #prod注册中心eureka地址ureka

seaweed:
  masterHost: "http://172.16.22.110:9333"