spring:
  redis:
    database: 0
    host: 172.16.9.16
    port: 6379
    password: redis
    timeout: 1000
  boot:
    admin:
      url: http://172.16.9.31:9625
      client:
        prefer-ip: true
      api-path: instances

#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.21:9602/eureka/,http://172.16.9.20:9602/eureka/,http://172.16.9.19:9602/eureka/"  #开发注册中心eureka地址

seaweed:
  masterHost: "172.16.9.15:9333"

druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_dev.properties