spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.22.106:3306/gtobusinessdb?characterEncoding=utf8&useSSL=true
      username: root
      password: a111111
      max-active: 20
      min-idle: 8
      initial-size: 10
      validation-query: SELECT 'x'
      filter:
        stat:
          enabled: true
  redis:
    database: 0
    host: 172.16.22.102
    port: 6379
    password: redis
    timeout: 1000
#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.100.103:9602/eureka/,http://172.16.100.104:9602/eureka/"  #prod注册中心eureka地址ureka

seaweed:
  masterHost: "http://172.16.22.110:9333"