server:
  port: 6011
  context-path: /

spring:
  application:
    name: support-center-employee-site-service
  profiles:
    active: fat
  cloud:
    stream:
      bindings:
        common_taskservice_af_empin_channel:
          destination: common_taskservice_af_empin # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        common_taskservice_af_empout_channel:
          destination: common_taskservice_af_empout # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        common_taskservice_af_emp_make_up_channel:
          destination: common_taskservice_af_emp_make_up # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        common_taskservice_af_emp_company_change_channel:
          destination: common_taskservice_af_emp_company_change # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        common_taskservice_af_emp_agreement_adjust_channel:
          destination: common_taskservice_af_emp_agreement_adjust # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        common_taskservice_af_emp_agreement_update_channel:
          destination: common_taskservice_af_emp_agreement_update # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        pay_apply_pay_status_stream_channel:
          destination: pay-apply-pay-status-stream # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        common_taskservice_af_company_social_account_once_channel:
          destination: common_taskservice_af_company_social_account_once # topic name
          group: ${spring.application.name}
          #content-type: application/json
          consumer:
            partitioned: true
        emp_employment_output_channel:
          destination: employee_management_service_af_ukey_feedback # topic name
          content-type: application/json
          producer:
            partitionCount: 1

  http:
    multipart:
      enabled: true
      max-file-size: 2MB
###################  spring cloud eureka  ###################
eureka:
  instance:
    lease-expiration-duration-in-seconds: 40
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapping*/*Mapper.xml
  typeAliasesPackage: com.ciicsh.gto.afsupportcenter.employmanagement.employcommandservice.entity
  plugins:
    - catMybatisInterceptor
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

app:
  id: 10006002

endpoints:
  shutdown:
    enabled: true
    sensitive: false
  health:
    enabled: true

management:
  security:
    enabled: false
  port: 6012
  context-path: /admin

http:
  multipart:
  enabled: true
  max-file-size: 2MB