server:
  port: 6012
  context-path: /

spring:
  application:
    name: support-center-soc-job
  profiles:
    active: dev
  cloud:
    stream:
      bindings:
        soc_report_input_channel:
          destination: af_soc_report_generate #topic name
          content-type: application/json
          group: ${spring.application.name} #consumer group
          consumer:
            partitioned: true
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 40
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.afsupportcenter.socjob.entity
  plugins:
    - catMybatisInterceptor

  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      map-underscore-to-camel-case: true
      cache-enabled: false
#xxl-job配置
logging:
  config: classpath:logback.xml
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: soc-job-executor
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken: