spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.9.53:3306/gtobusinessdb?useUnicode=true&useSSL=true&amp;characterEncoding=UTF-8
      username: root
      password: ciicit!#%
      max-active: 20
      min-idle: 8
      initial-size: 10
      validation-query: SELECT 'x'
      filter:
        stat:
          enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.9.55:9092
          zk-nodes: 172.16.9.55:2181,172.16.9.56:2181,172.16.9.57:2181

#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.56:9602/eureka"  #prod注册中心eureka地址ureka