spring:
  boot:
    admin:
      url: http://172.16.9.24:9625
      client:
        prefer-ip: true
      api-path: instances

#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.24:9602/eureka,http://172.16.9.25:9602/eureka"  #fat注册中心eureka地址

druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_test.properties