spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.22.106:3306/gtobusinessdb?characterEncoding=utf8&useSSL=true
      username: root
      password: a111111
      max-active: 20
      min-idle: 8
      initial-size: 10
      validation-query: SELECT 'x'
      filter:
        stat:
          enabled: true
  boot:
    admin:
      url: http://172.16.100.103:9625

#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.100.103:9602/eureka/,http://172.16.100.104:9602/eureka/"  #prod注册中心eureka地址ureka

druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_prd.properties