spring:
  boot:
    admin:
      url: http://172.16.9.31:9625
#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.21:9602/eureka/,http://172.16.9.20:9602/eureka/,http://172.16.9.19:9602/eureka/"  #开发注册中心eureka地址

druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_dev.properties