info:
  app:
    name: 支持中心证件管理Site后端服务模块
    version: 1.0.0
    description: 支持中心证件管理Site后端服务模块
spring:
  application:
    name: afsupport-center-credentials-command-service
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true

###################  spring cloud eureka  ###################
eureka:
  instance:
    lease-expiration-duration-in-seconds: 40
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.afsupportcenter.credentialscommandservice.customer
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false


server:
  port: 6025

app:
  id: 10006014
endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false
  port: 6026
  context-path: /admin