spring:
  datasource:
    url: jdbc:mysql://172.16.9.15:3306/gtobusinessdb?characterEncoding=utf8&useSSL=true
    username: root
    password: a111111

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://172.16.9.19:9600/eureka,http://172.16.9.20:9600/eureka,http://172.16.9.21:9600/eureka"
  instance:
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 40
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}

logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.ciicsh.zorro.salarymanagementwebservice: DEBUG
    org.mybatis: DEBUG