spring:
  application:
    name: afsupport-center-credentials-command-service
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**.xml
  type-aliases-package: com.ciicsh.gto.afsupportcenter.credentialscommandservice.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false


server:
  port: 9000

app:
  id=10009999
endpoints:
  shutdown:
    enabled: true
    sensitive: false
management:
  security:
    enabled: false
  port: 9000
  context-path: /admin