spring:
  redis:
    database: 0
    host: 172.16.9.65
    port: 6379
    password: redis
    timeout: 1000
  boot:
    admin:
      url: http://172.16.9.68:9625
      client:
        prefer-ip: true
      api-path: instances
  cloud:
    stream:
      kafka:
        binder:
          brokers: 172.16.9.64:9092
          zk-nodes: 172.16.9.64:2181


#spring cloud eureka
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.68:9602/eureka"  #fat注册中心eureka地址

seaweed:
  masterHost: "172.16.9.19:9333"


druid:
  configPath:  /data/appdatas/gt1/gtobusinessdb_lpt.properties