###################  项目启动端口  ###################
server:
  port: 6003
  context-path: /

###################  spring 配置  ###################
spring:
  application:
    name: support-center-soc-command-service
  profiles:
    active: develop
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.9.15:3306/gtobusinessdb?useUnicode=true&useSSL=true&amp;characterEncoding=UTF-8
      username: root
      password: a111111
      max-active: 20
      min-idle: 8
      initial-size: 10
      validation-query: SELECT 'x'
      filter:
        stat:
          enabled: true
  cloud:
        stream:
          kafka:
            binder:
              brokers: 172.16.9.17:9092,172.16.9.18:9092
              zk-nodes: 172.16.9.19:2181,172.16.9.20:2181,172.16.9.21:2181
          bindings:
            common_taskservice_af_empin-channel:
              destination: common_taskservice_af_empin # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true
            common_taskservice_af_empout-channel:
              destination: common_taskservice_af_empout # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true
            common_taskservice_af_charge_resume-channel:
              destination: common_taskservice_af_charge_resume # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true
            common_taskservice_af_charge_stop-channel:
              destination: common_taskservice_af_charge_stop # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true
            common_taskservice_af_nonlocal_to_sh-channel:
              destination: common_taskservice_af_nonlocal_to_sh # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true
            common_taskservice_af_sh_to_nonlocal-channel:
              destination: common_taskservice_af_sh_to_nonlocal # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true
            common_taskservice_af_emp_company_change-channel:
              destination: common_taskservice_af_emp_company_change # topic name
              group: ${spring.application.name}
              content-type: application/json
              consumer:
                partitioned: true

            soc_report_output_channel:
              destination: af_soc_report_generate # topic name
              content-type: application/json
              producer:
                partitionCount: 2

          instance-count: 2 # The number of deployed instances of an application.
                            # Must be set for partitioning and if using Kafka.
                            # used to partition data across different consumers.
          instance-index: 0
  http:
    multipart:
      enabled: true
      max-file-size: 2MB
###################  spring cloud eureka  ###################
eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.16.9.21:9602/eureka,http://172.16.9.20:9602/eureka,http://172.16.9.19:9602/eureka" #,http://172.16.9.21:9602/eureka
                         #" #本地开发环境eureka,http://172.16.9.19:9602/eureka
 #"http://172.16.9.21:9602/eureka,http://172.16.9.20:9602/eureka,http://172.16.9.19:9602/eureka" #本地开发环境eureka
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 40
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
###################  mybatis 配置  ###################
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapping*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ciicsh.gto.afsupportcenter.socialsecurity.soccommandservice.entity
  plugins:
    - catMybatisInterceptor
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

app:
  id: 10016002

endpoints:
  shutdown:
    #启用shutdown
    enabled: true
    #禁用密码验证
    sensitive: false
  health:
    enabled: true

#禁用安全验证
management:
  security:
    enabled: false
  port: 6004
  context-path: /admin

http:
  multipart:
  enabled: true
  max-file-size: 2MB